// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteReport(arg1) {
  return window['go']['main']['App']['DeleteReport'](arg1);
}

export function ExportAuditReport(arg1, arg2) {
  return window['go']['main']['App']['ExportAuditReport'](arg1, arg2);
}

export function GenerateHTMLReport(arg1, arg2) {
  return window['go']['main']['App']['GenerateHTMLReport'](arg1, arg2);
}

export function GetSavedReports(arg1) {
  return window['go']['main']['App']['GetSavedReports'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function OpenReport(arg1) {
  return window['go']['main']['App']['OpenReport'](arg1);
}

export function RunSystemAudit() {
  return window['go']['main']['App']['RunSystemAudit']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function ScanNetwork(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8) {
  return window['go']['main']['App']['ScanNetwork'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
