// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteReport(arg1:string):Promise<string>;

export function GenerateHTMLReport(arg1:Array<main.ScanResult>,arg2:string):Promise<string>;

export function GetSavedReports(arg1:string):Promise<Array<main.ReportFile>>;

export function LoadSettings():Promise<main.Settings>;

export function OpenReport(arg1:string):Promise<string>;

export function SaveSettings(arg1:main.Settings):Promise<string>;

export function ScanNetwork(arg1:string,arg2:string,arg3:boolean,arg4:boolean,arg5:number,arg6:number,arg7:string,arg8:string):Promise<Array<main.ScanResult>>;

export function StopScan():Promise<void>;
